### ISSUE TITLE
Change cursor in sort mode

### ISSUE THREAD

**Issue by bjarnef** [nathanwoulfe/stately#1]
When sort mode is active, can you then change the cursor type from ```pointer``` to ```move```?

e.g. set a class on the table when sort mode is active and then change then pointer i css for those buttons.

**Comment by nathanwoulfe** [comment]
Sure, makes sense

**Comment by nathanwoulfe** [comment]
Released v2.0.1 this morning - only change is the addition of the hover state for the sort handles
